### ISSUE TITLE
chaining transitions

### ISSUE THREAD

**Issue by eboody** [kenkunz/svelte-fsm#2]
Hey! 

I'd like to chain transitions to keep each state simple and to explicitly map out the various states so that someone else can look at the state machine as a map of what the app does, under what conditions, and in what order.

The documentation states that _enter's returns are ignored so im having to work around this. 

I dont exactly understand why it is that _enter should not allow transitions. Would it undermine the concept of finite state machines?

At the moment in order to chain things, im having to do something like this:

```
const machine = fsm('idle', {
	idle: {
		click() {
			return 'clicked';
		}
	},
	clicked: {
		_enter() {
			if (get(userStore)) this.userInfoAvailable();
			else this.userInfoMissing();
		},
		userInfoMissing: 'userInfoMissing',
		userInfoAvailable: 'userInfoAvailable'
	},
	userInfoMissing: {
		_enter() {
			//do a thing
		}
	},
	userInfoAvailable: {
		_enter() {
			// do another thing
		}
	}
});
```

its not clear to me from the documentation if I could accomplish this in a less verbose way. Am I missing something?

ideally what this would look like is this:

```
const machine = fsm('idle', {
	idle: {
		click() {
			return 'clicked';
		}
	},
	clicked: {
		_enter() {
			if (get(userStore)) return 'userInfoMissing';
			else return 'userInfoAvailable';
		},
	},
	userInfoMissing: {
		_enter() {
			//do a thing
		}
	},
	userInfoAvailable: {
		_enter() {
			// do another thing
		}
	}
});
```

**Comment by eboody** [comment]
derp. just figured out that i could do something like this instead:

```
	clicked: {
		_enter() {
			this.clicked();
		},
		clicked() {
			if (get(userStore)) return 'userInfoAvailable';
			else return 'userInfoMissing';
		}
	},
```

I am still curious about why _enter cant do transitions!

**Comment by kenkunz** [comment]
Hi @eboody,

Fair question. I'm concerned that supporting multiple transitions from a single event invocation could be confusing / lead to surprising results. The approach you're using above _technically_ works … but note that you will get two transitions in quick succession (resulting in two calls to every subscriber).

I'll need to give some thought to changing the API to more intentionally support this. I'm not hard-set against it … it just feels unusual to me to have multiple transitions from a single event.

While I don't know the details of your use case, I wonder if there's not a better approach. I generally avoid using the `get` method to retrieve store values (as recommended in the docs). In addition, the `clicked` state in your above code seems unnecessary – the two _real_ states are `userInfoMissing` and `userInfoAvailable` (`clicked` seems to be a transient state, only used for additional transition logic).

What if you used a subscription on the `userStore` to track the user states, then handle a `click` event differently from those two states? Something like:

```svelte
const machine = fsm('userInfoMissing', {
	userInfoMissing: {
		userChange(user) {
			if (user) return 'userInfoAvailable';
		},
		click() {
			// do a thing
		}
	},
	userInfoAvailable: {
		userChange(user) {
			if (!user) return 'userInfoMissing';
		},
		click() {
			// do another thing
		}
	}
});

$: machine.updateUser($userStore);
```

**Comment by eboody** [comment]
Thanks @kenkunz !

Yeah I think you're right. Still working through understanding how to abstract properly and your advice definitely moved the needle for me.

The way I visualized having multiple transitions from one event is kind of like a rube goldberg machine. One thing triggers the next; the machine itself changing states as the ball moves through the machine.

The main reason im doing this to avoid having one giant function that does all of the things but also to create a model that a coworker can easily go through to understand what the app is doing.

**Comment by kenkunz** [comment]
See [Store contract](https://svelte.dev/docs#Store_contract) and [svelte/store](https://svelte.dev/docs#svelte_store). Every time you call `get()`, you are
* creating a new subscription to the store
* which synchronously calls the subscriber with the current store value
* unsubscribing
* returning the value from the second step above

I think a better pattern would be to `subscribe` to the `userStore` directly, and invoke a `userChange` event on the FSM when the store calls your subscriber.

For example, after you have created your FSM, call `userStore.subscribe(stateMachine.userChange)`. Within the FSM, include appropriate `userChange` actions for a given state where it's needed. When the `click` event is invoked, your FSM already knows the user's login / permission state, so it just responds to the click appropriately.

Your user store subscription and click events are two independent inputs on your FSM. Each one acts on the FSM and in some cases causes it to transition.

Note that if you are subscribing to the `userStore` directly as suggested above, you _may_ need to also unsubscribe at some point – e.g., when the component that is using this FSM is destroyed (`onDestroy`). If the component is being used on a page in a context where it is never destroyed (e.g., it's not an SPA and navigating away from the page causes a full document re-load), then you should be OK not calling unsubscribe.

Hope this helps!

**Comment by j2l** [comment]
Hello,
I partially understand, because I'm learning FSM :)
Would you please write an example @kenkunz to help understand the mechanic, maybe in the docs?
Have a great day.

**Comment by kenkunz** [comment]
Hi @j2l – thanks for the feedback. I am busy working on a project with a deadline towards the end of Feb … I probably won't have a lot of time to update the docs until after that. I will give some thought to how to improve the docs and probably add some additional examples for various use cases.

**Comment by j2l** [comment]
I understand, thank you for your coming improvements when you have time :)

**Comment by morungos** [comment]
I know this is closed, but I needed it, so I've made a first draft of an implementation. It does make a few small external changes, so I've not yet made it a pull request, but I'd be very very happy to do so if you'd like. It's in a commit: https://github.com/morungos/svelte-fsm/commit/0955042122b95f94cfca9b62f574e5f23ed92200.  

The principle is: use `_enter()` to possibly return a new state. If there is one, we generate a new `_exit()`/`_enter()` pair, and continue until we don't get a value back from `_enter()`. At that point, if the new state is different from the old state, we can inform subscribers via a true event. it's not ideal, but does what I need, and is close enough to automatic transitions in state charts to be useful.

The most consequential changes are: 

1. It now expects `_enter()` to return a meaningful value -- this could be tweaked to signal differently, say via a passed function in the event metadata. Chances are, naively, this would break existing uses.
2. The `_enter()` call is now before the subscribers are informed, not after. This is explicitly tested, so it's serious. But I don't think it's necessarily wrong. My guess is this won't break existing uses, though. 

The benefit of this is that we can have internal states that aren't communicated to Svelte or such, but which make the flow simpler than attempting to fold it into more complex actions.
