### ISSUE TITLE
documentation doesn't describe how to pass an arguments

### ISSUE THREAD

**Issue by eboody** [kenkunz/svelte-fsm#3]
The documentation has the from, to, event, and args parameters that get passed to _enter but does not describe how one actually passes arguments from one state to another.

**Comment by kenkunz** [comment]
Hi again!

This is briefly mentioned in the **Actions** and **Event invocation** sections, but I agree it could be made clearer. Simple example:

```javascript
const machine = fsm('initial', {
	initial: {
		actionWithArgs(a, b) {
			console.log(a, b);
		}
	}
});

machine.actionWithArgs(100, 'hello');
// => 100 hello
```

I'll keep the issue open until I have a chance to improve the docs.

Cheers,
Ken

**Comment by eboody** [comment]
Hello again @kenkunz ! Actually my confusion was a result of what you said was an unusual use of the fsm model; Having one action creating a chain of transitions to multiple states.

I actually figured it out like this:

```
	initial: {
		_enter() {
                        const a = "a";
                        const b = "b"
			this.create(a, b);
		},
		create(a, b) {
			return 'anotherState';
		}
	},
	anotherState: {
		_enter({ args }) {
			console.log(args); //prints ["a", "b"]
		}
	}
```

**Comment by kenkunz** [comment]
I updated the docs to make `args` passing clearer.

Thanks again!
