### ISSUE TITLE
npm 7.0 requirement

### ISSUE THREAD

**Issue by lukasIO** [kenkunz/svelte-fsm#7]
Hi, 

unfortunately the engine requirement of npm > 7.0 is breaking an azure pipeline for us. 

Is there a reason for this package to require 7.0 as a minimum version? The azure pipeline only provides a 6.14 version...

Thanks in advance!

**Comment by kenkunz** [comment]
Hi @lukasIO – thanks for reporting this, and sorry for not commenting sooner. I'll test with a lower npm version and downgrade the minimum `engines` requirement if possible.
